# Tell Travis the project language.
language: c

# Route to the container-based infrastructure for a faster build.
sudo: false

# Branch whitelist.
branches:
  only:
    - master

# Install dependencies.
addons:
  apt:
    packages: splint
  homebrew:
    packages: splint

# Choose compilers.
compiler:
  - clang
  - gcc

# Build matrix.
matrix:
  include:
    - os: linux
    - os: osx
