# Tell Travis the project language.
language: c

# Route to the container-based infrastructure for a faster build.
sudo: false

# Branch whitelist.
branches:
  only:
    - master

# Choose operating systems.
os:
  - linux
  - osx

# Choose compilers.
compiler:
  - clang
  - gcc

# Install dependencies.
addons:
  apt:
    packages:
      - check
      - splint
  homebrew:
    packages:
      - check
      - splint

# Override default script.
script:
  - cmake .
  - splint `cat src/.splint-sources`
  - cmake --build .
  - ctest --output-on-failure
